use_frameworks!


target 'Example-iOS' do
  platform :ios, '9.0'
  pod 'SnapLayout', :path => '../'
end

target 'Example-MacOS' do
  platform :osx, '10.11'
  pod 'SnapLayout', :path => '../'
end

target 'SnapLayout_ExampleTests' do
   platform :ios, '9.0'
   pod 'SnapLayout', :path => '../'
   inherit! :search_paths
end
