use_frameworks!


target 'Example-iOS' do
  platform :ios, '9.0'
  pod 'SnapLayout', :path => '../'
end

target 'Example-MacOS' do
  platform :osx, '10.11'
  pod 'SnapLayout', :path => '../'
end

target 'SnapLayout_ExampleTests' do
   platform :ios, '9.0'
   pod 'SnapLayout', :path => '../'
   inherit! :search_paths
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
  end